# Generated by Django 4.2 on 2023-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='eage',
            field=models.IntegerField(),
        ),
    ]
